"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userController_1 = require("../controller/userController");
const router = (0, express_1.Router)();
router.post("/users", (request, response) => { userController_1.default.createUser(request, response); });
router.get("/users/:id", (request, response) => { userController_1.default.getUserById(request, response); });
router.get("/users", (_, response) => { userController_1.default.getAllUsers(response); });
router.put("/users/:id", (request, response) => { userController_1.default.updateUser(request, response); });
router.delete("/users/:id", (request, response) => { userController_1.default.deleteUser(request, response); });
exports.default = router;
